### ISSUE TITLE
Discord spam mitigation for two-stage onboarding

### ISSUE THREAD

**Issue by kfarwell** [flirtual/flirtual#165]
When users include their Discord username in their bio, they get spam. The volume of spam may increase with https://github.com/flirtual/flirtual/issues/145 when users can browse profiles before finishing their own and confirming their email. To mitigate this:

```[tasklist]
### Tasks
- [ ] https://github.com/flirtual/flirtual/issues/180
- [ ] https://github.com/flirtual/flirtual/issues/183
- [ ] https://github.com/flirtual/flirtual/issues/182
- [ ] https://github.com/flirtual/flirtual/issues/181
```
